server:
 port: 8888
 
spring:
 application:
  name: springcloud-configserver
 profiles:
  active: prod
  
# GITHUB - CONFIGURATION REPO
 cloud:
  config:
   server:
    git:
     uri: https://github.com/kishore-rajkumar/springcloud-config-server.git
     clone-on-start: true
